# Generated by Django 3.0.7 on 2020-06-09 10:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_number', models.IntegerField()),
                ('quote_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('salse_person', models.CharField(max_length=255)),
                ('quote_status', models.CharField(choices=[('IQ', 'Initial Quote'), ('QS', 'Quote Send'), ('WP', 'Waiting for Payment'), ('QC', 'Completed')], default='FIXED', max_length=2)),
                ('quote_info', jsonfield.fields.JSONField(default=dict)),
                ('quote_summary', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tbl_estiamtes',
            },
        ),
    ]
